## Atividade 3 (Letra c) - Modelos Mistos

In [1]:
import numpy as np
import pandas as pd

In [2]:
#matriz = np.array([[0,0,0,0],[0,1, 0 ,0],[0,2,0,0],[0,3,1,2],[0,4,0,0],[0,5,3,2],[0,6,4,2],[0,7,5,2],[0,8,7,6]])
#matriz = np.array([[0,0,0,0],[0,1,0,0],[0,2,1,0],[0,3,1,2],[0,4,3,2]])
matriz = np.array([[0,0,0,0],[0,1,0,0],[0,2,0,0],[0,3,0,0],[0,4,1,2],[0,5,1,2],[0,6,1,2],[0,7,4,6],[0,8,3,5],[0,9,4,6],[0,10,3,2],[0,11,3,7],[0,12,8,7],[0,13,9,2],[0,14,3,7]])
matriz

array([[ 0,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  4,  1,  2],
       [ 0,  5,  1,  2],
       [ 0,  6,  1,  2],
       [ 0,  7,  4,  6],
       [ 0,  8,  3,  5],
       [ 0,  9,  4,  6],
       [ 0, 10,  3,  2],
       [ 0, 11,  3,  7],
       [ 0, 12,  8,  7],
       [ 0, 13,  9,  2],
       [ 0, 14,  3,  7]])

##### Rounds

In [3]:
n_individuos = matriz.shape[0]-1
v = np.zeros((n_individuos+1))
u = np.zeros((n_individuos+1))
d_ = np.zeros((n_individuos+1))
d_i = np.zeros((n_individuos+1))
l = []
#i=1
for i in range(1,n_individuos+1):
    print('------------------')
    s = matriz[i,2]
    d = matriz[i,3]
    #print(s,d)
    if (s==0) & (d==0):
        v[i] = 1
    elif (s>0) & (d>0):
        #print('aqui')
        v[i] = (1-((1/4)*(u[s]+u[d])))**(1/2)
    elif (s>0) & (d==0):
        v[i] = (1-(1/4)*(u[s]))**(1/2)
    elif (s==0) & (d>0):
        v[i] = (1-(1/4)*(u[d]))**(1/2)
    
    ##u    
    j=i
    u[j] = u[j]+v[j]**2

    j = i+1
    while j<=n_individuos:
    #while j<=4:
        s = matriz[j,2]
        d = matriz[j,3]
        #print('i=',i,'s=',s,'d=',d,'j=',j)
        if (s<i) & (d<i):
            v[j] = 0
            #print('aqui')
        elif (i<=s) & (i<=d):
            v[j] = ((1/2)*(v[s]))+((1/2)*(v[d]))
            #print('aqui1')
        elif (d<i) & (i<=s):
            #print(v[s])
            v[j] = (1/2)*(v[s])
            #print('aqui2')
        elif (s<i) & (i<=d):
            v[j] = (1/2)*(v[d])
            #print('aqui3')

        u[j] = u[j]+(v[j]**2)
        #print('u{} = {}'.format(j,u[j]))
        j += 1
    l.append(np.copy(v[1:]))
    d_[i] = v[i]**2
    d_i[i] = v[i]**(-2)
    
    print('Rodada ',i)
    print('v = ',v)
    print('u = ',u)
    print('d = ',d_)
    print('d_i = ',d_i)

------------------
Rodada  1
v =  [0.    1.    0.    0.    0.5   0.5   0.5   0.5   0.25  0.5   0.    0.25
 0.375 0.25  0.25 ]
u =  [0.       1.       0.       0.       0.25     0.25     0.25     0.25
 0.0625   0.25     0.       0.0625   0.140625 0.0625   0.0625  ]
d =  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
d_i =  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------
Rodada  2
v =  [0.    1.    1.    0.    0.5   0.5   0.5   0.5   0.25  0.5   0.5   0.25
 0.375 0.75  0.25 ]
u =  [0.      1.      1.      0.      0.5     0.5     0.5     0.5     0.125
 0.5     0.25    0.125   0.28125 0.625   0.125  ]
d =  [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
d_i =  [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------
Rodada  3
v =  [0.   1.   1.   1.   0.   0.   0.   0.   0.5  0.   0.5  0.5  0.25 0.
 0.5 ]
u =  [0.      1.      1.      1.      0.5     0.5     0.5     0.5     0.375
 0.5     0.5     0.375   0.34375 0.625   0.375  ]
d =  [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.

## Montando matriz

In [10]:
l = np.asarray(l)
l = np.tril(np.transpose(l))
print(pd.DataFrame(l))

     0    1    2      3      4      5      6      7      8      9      10  \
0   1.0  0.0  0.0  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000   
1   0.0  1.0  0.0  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000   
2   0.0  0.0  1.0  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000   
3   0.0  0.0  0.0  0.707  0.000  0.000  0.000  0.000  0.000  0.000  0.000   
4   0.0  0.0  0.0  0.000  0.707  0.000  0.000  0.000  0.000  0.000  0.000   
5   0.0  0.0  0.0  0.000  0.000  0.707  0.000  0.000  0.000  0.000  0.000   
6   0.0  0.0  0.0  0.000  0.000  0.000  0.707  0.000  0.000  0.000  0.000   
7   0.0  0.0  0.0  0.000  0.000  0.000  0.000  0.707  0.000  0.000  0.000   
8   0.0  0.0  0.0  0.000  0.000  0.000  0.000  0.000  0.707  0.000  0.000   
9   0.0  0.0  0.0  0.000  0.000  0.000  0.000  0.000  0.000  0.707  0.000   
10  0.0  0.0  0.0  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.661   
11  0.0  0.0  0.0  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000   

In [228]:
A = np.matmul(l,np.transpose(l))
A

array([[1.    , 0.    , 0.    , 0.5   , 0.5   , 0.5   , 0.5   , 0.25  ,
        0.5   , 0.    , 0.25  , 0.375 , 0.25  , 0.25  ],
       [0.    , 1.    , 0.    , 0.5   , 0.5   , 0.5   , 0.5   , 0.25  ,
        0.5   , 0.5   , 0.25  , 0.375 , 0.75  , 0.25  ],
       [0.    , 0.    , 1.    , 0.    , 0.    , 0.    , 0.    , 0.5   ,
        0.    , 0.5   , 0.5   , 0.25  , 0.    , 0.5   ],
       [0.5   , 0.5   , 0.    , 1.    , 0.5   , 0.5   , 0.75  , 0.25  ,
        0.75  , 0.25  , 0.375 , 0.5   , 0.625 , 0.375 ],
       [0.5   , 0.5   , 0.    , 0.5   , 1.    , 0.5   , 0.5   , 0.5   ,
        0.5   , 0.25  , 0.25  , 0.5   , 0.5   , 0.25  ],
       [0.5   , 0.5   , 0.    , 0.5   , 0.5   , 1.    , 0.75  , 0.25  ,
        0.75  , 0.25  , 0.375 , 0.5   , 0.625 , 0.375 ],
       [0.5   , 0.5   , 0.    , 0.75  , 0.5   , 0.75  , 1.25  , 0.25  ,
        0.75  , 0.25  , 0.625 , 0.75  , 0.625 , 0.625 ],
       [0.25  , 0.25  , 0.5   , 0.25  , 0.5   , 0.25  , 0.25  , 1.    ,
        0.25  , 0.375 , 0

## Inversa de A

In [229]:
A_i = np.zeros((n_individuos+1,n_individuos+1))
for i in range(1,n_individuos+1):
    A_inv = np.zeros((n_individuos+1,n_individuos+1))
    s = matriz[i,2]
    d = matriz[i,3]
    if (s>0) & (d>0):
        A_inv[i,i] = d_i[i]
        A_inv[i,s] = A_inv[i,d] = A_inv[s,i] = A_inv[d,i] = (-1/2)*d_i[i]
        A_inv[s,s] = A_inv[s,d] = A_inv[d,s] = A_inv[d,d] = (1/4)*d_i[i]
    elif (s>0) & (d==0):
        A_inv[i,i] = d_i[i]
        A_inv[i,s] = A_inv[s,i] = (-1/2)*d_i[i]
        A_inv[s,s] = (1/4)*d_i[i]
    elif (s==0) & (d>0):
        A_inv[i,i] = d_i[i]
        A_inv[i,d] = A_inv[d,i] = (-1/2)*d_i[i]
        A_inv[d,d] = (1/4)*d_i[i]
    elif (s==0) & (d==0):
        A_inv[i,i] = d_i[i]
    print('--------------------------Individuo {}--------------------------'.format(i))
    A_i += A_inv
    print(A_i[1:,1:])    

--------------------------Individuo 1--------------------------
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
--------------------------Individuo 2--------------------------
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.